title: Leaf Blog
iconURL: assets/default-icon.png
# for a clean URL
permalink: :slug

social:
  twitter: _SupunKavinda
  github: SupunKavinda

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
##mi id es 10000
#hyvor_talk_website_id: 14
#google_analytics: UA-NNNNNNNN-N
hyvor_talk_website_id: 10000
###google_analytics: UA-NNNNNNNN-N
